### ISSUE TITLE
[Feature] 導入 commitlint 與制定 commit 規範

### ISSUE THREAD

**Issue by Bosh-Kuo** [Bosh-Kuo/docusaurus-dev-notes#5]
## Describe the feature request

目前 git commit log 沒有定義明確規則，也沒有使用工具強制限制 commit log 格式。
參考 [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) 定義本專案的 commit log 規則，並使用 commitlint 工具檢核 commit log 格式

## TODO

- [ ] 添加 CONTRIBUTING.md 定義 commit log 規則
- [ ] 導入 commitlint, husky 工具
- [ ] 導入 Prompt 工具
